Repository metwork-framework/github_organization_management, pull requests merged in 2020-09, with the labels that each got.

#10 fix: fix title regex and branch protection
  common_files/mergify.yml
  config.tf.jinja2
Labels: Status: Review Needed

#14 feat: changelog generation for integration-level >=4 (part1)
  .github/workflows/changelogs.sh
  .github/workflows/changelogs.yml
  bin/latest_release.py
  releases.json
Labels: Status: Merge Now, Status: Review Needed

#17 build: add mfextaddons trigger on master branch
  common_files/docker-mfxxx-yyy-buildimage_drone.yml
Labels: Status: Review Needed

#18 build: fix typo
  common_files/docker-mfxxx-yyy-buildimage_drone.yml
Labels: Status: Merge Now

#19 feat: add cron to copy integration branch
  .github/workflows/copy_integration_master.yml
Labels: Status: Review Needed

#21 feat: changelog generation for release branches
  .github/workflows/changelogs.sh
  bin/active_releases.py
  releases.json
Labels: Status: Merge Now, Status: Review Needed

#23 Update changelogs.sh
  .github/workflows/changelogs.sh
Labels: Status: Review Needed

#27 build: fix some concurrency issues in changelog generation
  bin/changelogs.sh
  bin/get_short_random_hexa.py
Labels: Status: Merge Now, Status: Review Needed
